### ISSUE TITLE
Migration to version 12.0

### ISSUE THREAD

**Issue by jarmokortetjarvi** [futurable/account-invoicing#2]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0

# Modules to migrate

- [ ] account_dashboard_refund_buttons
- [ ] account_invoice_circulation
- [ ] account_invoice_circulation_mandatory_analytic
- [ ] account_invoice_client_order_ref
- [ ] account_invoice_commission
- [ ] account_invoice_default_my
- [ ] account_invoice_default_parent
- [ ] account_invoice_disable_due_date_auto_update
- [ ] account_invoice_disable_invoice_reference_check
- [ ] account_invoice_invoice_address
- [ ] account_invoice_invoice_address_defaults
- [ ] account_invoice_line_margin_percent
- [ ] account_invoice_line_total
- [ ] account_invoice_mandatory_payment_term
- [ ] account_invoice_margin
- [ ] account_invoice_margin_from_sale
- [ ] account_invoice_margin_ignore
- [ ] account_invoice_margin_in_tree
- [ ] account_invoice_margin_percent
- [ ] account_invoice_merge_line_info
- [ ] account_invoice_merge_never_merge_lines
- [ ] account_invoice_merge_ordered
- [ ] account_invoice_notice_period
- [ ] account_invoice_order_number_in_comments
- [ ] account_invoice_overdue_interest
- [ ] account_invoice_partner_quick_insert
- [ ] account_invoice_partner_strict
- [ ] account_invoice_promised_delivery_range
- [ ] account_invoice_refund_preserve_analytic_tags
- [ ] account_invoice_review
- [ ] account_invoice_transmit_method_einvoice
- [ ] account_invoice_transmit_type_translatable
- [ ] account_invoice_vendor_invoice_to_sale
- [ ] account_invoice_vendor_invoice_tree_untaxed
- [ ] account_refund_form_total_string
- [ ] account_refund_line_negative_warning
